#!/bin/bash

# test: Test debops.elasticsearch
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences debops.etc_services debops.ferm debops.java debops.secret debops.elastic_co


echo "Ansible facts"
ansible all -m setup -b

echo "java -version"
java -version

# https://askubuntu.com/questions/625979/
echo "Purge current Java"
sudo rm -vrf /var/lib/binfmts/jar
apt-cache search java | awk '{print($1)}' | grep -E -e '^(ia32-)?(sun|oracle)-java' -e '^openjdk-' -e '^icedtea' -e '^(default|gcj)-j(re|dk)' -e '^gcj-(.*)-j(re|dk)' -e 'java-common' | xargs sudo apt-get -y --purge remove
sudo apt-get -y autoremove
dpkg -l | grep ^rc | awk '{print($2)}' | xargs sudo apt-get -y purge
sudo bash -c 'ls -d /home/*/.java' | xargs sudo rm -rf
sudo rm -rf /usr/lib/jvm/*

echo "Install OpenJDK 8"
sudo add-apt-repository -y ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get -y install openjdk-8-jdk

echo "java -version"
java -version

stop elasticsearch
purge elasticsearch


assert_playbook_check_runs
assert_playbook_idempotent


echo "apt-cache policy elasticsearch"
apt-cache policy elasticsearch

echo "netstat -lp"
netstat -lp

echo "Cluster state"
curl http://localhost:9200/_cluster/health

echo "Elasticsearch logs"
sudo bash -c 'cat /var/log/elasticsearch/*.log'


assert_path "/etc/elasticsearch/elasticsearch.yml"

assert_url "http://localhost:9200"


assert_docs
