#!/bin/bash

# test: Test debops.elasticsearch
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

ansible-galaxy -f install debops.etc_services debops.ferm debops.java debops.secret debops.elastic_co


stop elasticsearch
purge elasticsearch


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/elasticsearch/elasticsearch.yml"

assert_running "elasticsearch"

assert_url "http://localhost:9200"


assert_docs
