#!/bin/bash

# test: Test debops.kibana
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences debops.etc_services debops.ferm debops.secret debops.elastic_co


assert_playbook_check_runs
assert_playbook_idempotent


echo "apt-cache policy kibana"
apt-cache policy kibana

echo "netstat -lp"
netstat -lp

echo "Application state"
curl http://localhost.localdomain/


assert_path "/etc/kibana/kibana.yml"

assert_url "http://localhost.localdomain/"

assert_docs
