#!/bin/bash

# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences

assert_playbook_check_runs
assert_playbook_idempotent

if dpkg-query -W -f='${Status} ${Version}\n' git-annex-standalone
then
	pass "OK: git-annex-standalone is installed."
else
	fail "Not OK: git-annex-standalone is not installed."
fi

assert_docs
