#!/bin/bash

# test: Test debops.elastic_co
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


echo "Purge elasticsearch before installation"
sudo apt-get -y --purge remove 'elasticsearch*'


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences


assert_playbook_check_runs
assert_playbook_idempotent


echo "Status of APT preferences for Elastic packages"
echo "----------------------------------------------"
apt-cache policy elasticsearch kibana heartbeat


echo "Contents of the Ansible local facts"
echo "-----------------------------------"
/etc/ansible/facts.d/elastic_co.fact


assert_docs
