#!/bin/bash

# test: Test debops.nsswitch
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


echo "Contents of /etc/nsswitch.conf before playbook:"
cat /etc/nsswitch.conf


assert_playbook_check_runs
assert_playbook_idempotent


echo "Contents of /etc/nsswitch.conf after playbook:"
cat /etc/nsswitch.conf


assert_path "/etc/nsswitch.conf"
assert_docs
